Docs - prepare module for publishing on packagist
signify-nz/silverstripe-solr pull request #8
Opened 2024-11-17 20:49 UTC by sig-mmiddleton

Addressing issue #7 - update the docs in preparation for publishing this module on packagist.

2024-11-18 22:16 UTC, sig-peggy requested changes
Overall, looks pretty good! Just a few extra suggestions, many of which are optional and open for discussion :)

2024-11-18 22:16 UTC, sig-peggy commented on composer.json
> +    "docs": "https://firesphere.github.io/solr-docs"
I don't think we want to keep linking to the firesphere docs because we can't change them. There are already additional features in our version that have been noted in the docs within this repo that won't show up in the firesphere docs (unless they do ever get around to looking at the PRs I made months ago), plus all of the changes you've made for this work won't appear there.

2024-11-18 22:16 UTC, sig-peggy commented on docs/01-Installation.md
> +`composer require signify-nz/silverstripe-solr`
This name in the composer.json needs to be changed to match this.

2024-11-18 22:16 UTC, sig-peggy commented on docs/07-Customisation.md
> +The type mapping is defined in [`typemap.yml`](https://github.com/signify-nz/silverstripe-solr/blob/2.x/_config/typemap.yml).
Do we need this to be the full github URL including the version number? This seems like something we would be incredibly unlikely to remember to update if the type mapping changed in a later version. Since it's a file inside this repo, would a relative link work instead and keep people on whatever branch they're currently on?

2024-11-18 22:16 UTC, sig-peggy commented on docs/10-Suggestions.md
> +To set this up, have a look at [autosuggest proxy](https://github.com/signify-nz/silverstripe-solr/blob/2.x/client/proxy/autosuggest.php)
Same as above - can we use a relative link instead of a version specific one?

2024-11-18 22:16 UTC, sig-peggy commented on readme.md
>  More details can be found in the [docs](https://firesphere.github.io/solr-docs/01-Installation.html).
Again, I think these docs links should point to the files within this repo rather than the firesphere ones that won't be changed if we update things.
For the links that aren't to specific places within the documentation, it might help if we add a table of contents into the index file (or somewhere similar) so that the general documentation links go to an easy to navigate list of all the docs within the repo.

2024-11-18 22:16 UTC, sig-peggy commented on composer.json
Required: the 'name' must be changed to match what you've put with `composer require` in the docs
Additional optional changes:
- In the 'suggest' section, we may want to remove some - at the very least, I found the fluent submodule listed didn't actually work so we maybe don't want to suggest it (and possibly remove it from the docs as well?)
- in the 'support' section, we could add a 'security' link since we do have the security policy - see https://getcomposer.org/doc/04-schema.md#support
- would it be worth adding a 'replace' section to identify that this module should replace the firesphere one if that's in other module dependencies? - see https://getcomposer.org/doc/04-schema.md#replace

2024-11-18 22:16 UTC, sig-peggy commented on docs/template.html
Do we still need this file at all if our changes to documentation aren't going outside of the repo?

2024-11-20 03:42 UTC, sig-mmiddleton commented
Have addressed all of the above noted issues

2024-11-21 00:47 UTC, sig-peggy reviewed
These changes look good to me ✅ 
Expecting secondary review by another person before approval.

2024-12-05 04:33 UTC, sig-sam commented on readme.md
>  Solr8
Does the module also support Solr 9? If so, is it worth mentioning?

2024-12-05 04:33 UTC, sig-sam commented on docs/14-Contributing/01-Code-of-Conduct.md
> +The original module that this module was forked from has a code of conduct - see [Code-of-Conduct.](https://codeberg.org/Firesphere/silverstripe-solr/src/branch/main/docs/14-Contributing/)01-Code-of-
Is the "01-Code-of-Conduct.md" text at the end supposed to be there?

2024-12-05 04:34 UTC, sig-sam commented
Most of the code files have a `@copyright` annotation. Do we need to do anything about them?

2024-12-05 04:34 UTC, sig-sam commented
Do we also need to remove https://github.com/signify-nz/silverstripe-solr/blob/docs/publishable-docs/CODE_OF_CONDUCT.md?

2024-12-05 04:35 UTC, sig-sam commented
Do the unit tests pass?

2024-12-05 04:35 UTC, sig-sam commented
I can't create an image using the `Dockerfile`. We should probably raise an issue or remove it?

2024-12-05 04:36 UTC, sig-sam commented
What is the `.codeclimate.yml` file for?

2024-12-05 04:40 UTC, sig-sam commented
The conditions of the Lesser General Public License say that we need to "State changes". We should confirm what this means.

<img width="114" alt="conditions" src="https://github.com/user-attachments/assets/4374fc8c-c66c-4ae8-980c-4e032f5d4f9f">

See https://github.com/signify-nz/silverstripe-solr/blob/docs/publishable-docs/LICENSE.md

2024-12-05 04:51 UTC, sig-peggy commented
> Do the unit tests pass?

No - I have a note on [SIGIMM-19](https://signify.atlassian.net/browse/SIGIMM-19) about this issue. Unit tests in the original module were not kept up to date and are not compatible with PHPUnit 9 (or possibly PHP > 8). I tried briefly to get them working but it turned out to be a significant undertaking so will need to be tackled separately.

2024-12-05 20:56 UTC, sig-peggy commented
> Most of the code files have a `@copyright` annotation. Do we need to do anything about them?

and 

> The conditions of the Lesser General Public License say that we need to "State changes". We should confirm what this means.
> <img alt="conditions" width="114" src="https://private-user-images.githubusercontent.com/25677215/392655571-4374fc8c-c66c-4ae8-980c-4e032f5d4f9f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzEyMDcsIm5iZiI6MTczMzQzMDkwNywicGF0aCI6Ii8yNTY3NzIxNS8zOTI2NTU1NzEtNDM3NGZjOGMtYzY2Yy00YWU4LTk4MGMtNGUwMzJmNWQ0ZjlmLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDIwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWE1MWNkMWIxMWNmZmMyYTQ3NjZjZjhmNDJmZjVhYjRlYWE2NGVjMDcxZDBhMWRiNTBhODNhNGNhNzc2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RlrMv0a__9qz-PGUAQ6crU6jpQwk440Wqg3P9_-1fXw">
> 
> See https://github.com/signify-nz/silverstripe-solr/blob/docs/publishable-docs/LICENSE.md

[this answer seems helpful](https://opensource.stackexchange.com/a/8272) - It's not for the same license but the GNU v3 requirement seems like the same thing in different words to me (for reference, the GNU phrasing is "The work must carry prominent notices stating that you modified it, and giving a relevant date."). I also found [this one about GPL 3](https://opensource.stackexchange.com/a/7712) but it's not as detailed an answer.

I think this means that we can add an additional copyright line to the existing copyright notices saying we modified it this year and that would also, theoretically, cover the 'state changes' requirement. If we need a more specific date, apparently the first commit I made was on 3 September.

2024-12-08 20:17 UTC, sig-steve commented
> Most of the code files have a `@copyright` annotation. Do we need to do anything about them?

The related docblocks look like this:

```php
/**
 * class SchemaFactory|Firesphere\SolrSearch\Services\SchemaFactory Base service for generating a schema
 *
 * @package Firesphere\Solr\Search
 * @author Simon `Firesphere` Erkelens; Marco `Sheepy` Hermo
 * @copyright Copyright (c) 2018 - now() Firesphere & Sheepy
 */
```

My opinion is that for files we modify, we should be adding ourselves as an author.

```php
/**
 * class SchemaFactory|Firesphere\SolrSearch\Services\SchemaFactory Base service for generating a schema
 *
 * @package Firesphere\Solr\Search
 * @author Simon `Firesphere` Erkelens; Marco `Sheepy` Hermo
 * @copyright Copyright (c) 2018 - now() Firesphere & Sheepy
 * @author Signify Ltd <info@signify.co.nz>
 */
```

I don't know whether we should be asserting copyright over our modifications. The original copyright covers the upstream source, but not our modifications, but our modifications are unlikely to be useful on their own.

2024-12-08 20:53 UTC, sig-steve commented
LGPL is a set of tweaks to the GPL, so the actual relevant section is [GPL section 5](https://www.gnu.org/licenses/gpl-3.0.en.html#section5).

The relevant text is in 5a: _The work must carry prominent notices stating that you modified it, and giving a relevant date._

Based on that, the amended docblock is something like:

```php
/**
 * class SchemaFactory|Firesphere\SolrSearch\Services\SchemaFactory Base service for generating a schema
 *
 * @package Firesphere\Solr\Search
 * @author Simon `Firesphere` Erkelens; Marco `Sheepy` Hermo
 * @copyright Copyright (c) 2018 - now() Firesphere & Sheepy
 * @author Signify Ltd <info@signify.co.nz>
 * Signify Ltd modified code in Dec 2024
 */
```

2024-12-08 21:58 UTC, sig-peggy approved these changes
These all look good to me 👍

2024-12-08 23:35 UTC, sig-sam requested changes
One minor issue. Otherwise, things are looking good.

2024-12-08 23:35 UTC, sig-sam commented on readme.md
> +Solr9 is supported
This is a bit difficult to read as it's formatted as one long sentence. See https://github.com/signify-nz/silverstripe-solr/tree/docs/publishable-docs

2024-12-09 00:38 UTC, sig-sam commented
Looks good. No further changes needed.

2024-12-09 00:38 UTC, sig-sam approved these changes

2024-12-09 03:23 UTC, sig-peggy commented
Moved to new repository to keep the different package names separate as required by composer.
These changes are now in PR https://github.com/signify-nz/silverstripe-solr-search/pull/1

2024-12-09 03:23 UTC, closed without merging